<?php

namespace Tests\Feature\Http\Controllers\Auth;

use App\Models\User;
use Faker\Factory;
use Illuminate\Foundation\Testing\RefreshDatabase;
use Tests\TestCase;

class PassportAuthControllerTest extends TestCase
{
    use RefreshDatabase;

    public function setUp (): void
    {
        parent::setUp(); // TODO: Change the autogenerated stub

        $this->artisan('passport:install');
    }

    /**
     * @test
     */
    public function can_authenticate ()
    {
        $faker = Factory::create();

        $user = factory(User::class)->create([
            'email' => $faker->email,
            'password' => bcrypt(12345)
        ]);

        $response = $this->json('POST', '/passport/token/create', [
            'email' => $user->email,
            'password' => $user->password
        ]);

        $response->assertStatus(201)
            ->assertJsonStructure(['token']);
    }
}
